import * as React from 'react';
import { Button, Card } from '../common';
import { ICONS } from '../../assets';
import logo from '../../assets/svg/logo.svg';
import placeholder from '../../assets/images/placeholder.png';

const DemoAssets: React.FC = () => {
  return (
    <div className="p-8 space-y-8">
      {/* Enhanced Button with Icons */}
      <div>
        <h2 className="text-xl font-bold mb-4 text-white">Enhanced Button with Icons</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <Button icon="Star" variant="primary">Starred Button</Button>
          <Button icon="Heart" iconPosition="right" variant="outline">Liked Button</Button>
          <Button icon="PlusCircle" iconSize="lg" variant="secondary">Add New</Button>
          <Button icon="Trash2" variant="danger" iconSize="sm">Delete</Button>
          <Button icon="Download" variant="ghost">Download</Button>
          <Button icon="Upload" iconPosition="right" variant="primary">Upload File</Button>
        </div>
      </div>

      {/* Card with Icons */}
      <div>
        <h2 className="text-xl font-bold mb-4 text-white">Card with Icons</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <Card 
            icon="Brain" 
            title="AI Quiz" 
            subtitle="Generated by artificial intelligence"
            hoverable
          >
            <p className="text-gray-300">Advanced quiz generation using AI technology.</p>
          </Card>
          <Card 
            icon="Trophy" 
            title="Leaderboard" 
            subtitle="Top performers"
            hoverable
          >
            <p className="text-gray-300">See how you rank against other players.</p>
          </Card>
          <Card 
            icon="Target" 
            title="Goals" 
            subtitle="Track your progress"
            hoverable
          >
            <p className="text-gray-300">Set and achieve your learning goals.</p>
          </Card>
        </div>
      </div>

      {/* SVG Logo */}
      <div>
        <h2 className="text-xl font-bold mb-2 text-white">SVG Logo</h2>
        <img src={logo} alt="Logo SVG" className="h-12 w-12" />
      </div>

      {/* Image Asset */}
      <div>
        <h2 className="text-xl font-bold mb-2 text-white">Image Asset</h2>
        <img src={placeholder} alt="Placeholder" className="h-16 w-16 rounded shadow" />
      </div>

      {/* Custom Font Usage */}
      <div>
        <h2 className="text-xl font-bold mb-2 text-white">Custom Font (Roboto)</h2>
        <p style={{ fontFamily: 'Roboto, Arial, sans-serif', fontSize: 20, color: 'white' }}>
          This text is using the Roboto font (if loaded).
        </p>
      </div>

      {/* Icon Categories Demo */}
      <div>
        <h2 className="text-xl font-bold mb-4 text-white">Icon Categories Demo</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">
          <Button icon="Home" variant="ghost" size="sm">Home</Button>
          <Button icon="BookOpen" variant="ghost" size="sm">Quiz</Button>
          <Button icon="Trophy" variant="ghost" size="sm">Trophy</Button>
          <Button icon="Target" variant="ghost" size="sm">Goals</Button>
          <Button icon="User" variant="ghost" size="sm">Profile</Button>
          <Button icon="Settings" variant="ghost" size="sm">Settings</Button>
        </div>
      </div>
    </div>
  );
};

export default DemoAssets;