import * as React from 'react';
import { Trophy, ClipboardList, ChartLine, Shapes, Bot, RefreshCw, Users, Clock } from 'lucide-react';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Navigation, Pagination, A11y } from 'swiper/modules';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

const features = [
  {
    icon: <Trophy className="text-yellow-400 w-12 h-12 transition-transform duration-200 group-hover:scale-110" />, title: 'Gamification', desc: 'Engage with streaks, badges, and achievements that motivate you to stay consistent and celebrate your learning milestones.'
  },
  {
    icon: <ClipboardList className="text-blue-400 w-12 h-12 transition-transform duration-200 group-hover:scale-110" />, title: 'Exam Simulations', desc: 'Access a test bank with previous year questions and timed mock tests that prepare you for real exam conditions.'
  },
  {
    icon: <ChartLine className="text-purple-400 w-12 h-12 transition-transform duration-200 group-hover:scale-110" />, title: 'Smart Dashboard', desc: 'Your personalized performance hub with analytics and tailored recommendations to enhance your study efforts.'
  },
  {
    icon: <Shapes className="text-green-400 w-12 h-12 transition-transform duration-200 group-hover:scale-110" />, title: 'Versatile Question Types', desc: 'Master concepts through diverse formats including MCQs, matching pairs, and interactive problem-solving exercises.'
  },
  {
    icon: <Bot className="text-orange-400 w-12 h-12 transition-transform duration-200 group-hover:scale-110" />, title: 'AI-Generated Quizzes', desc: 'Experience personalized quizzes generated by AI to target your learning gaps and enhance retention.'
  },
  {
    icon: <RefreshCw className="text-teal-400 w-12 h-12 transition-transform duration-200 group-hover:scale-110" />, title: 'Adaptive Learning', desc: 'Our platform adapts to your learning style and pace, ensuring a customized educational experience.'
  },
  {
    icon: <Users className="text-indigo-400 w-12 h-12 transition-transform duration-200 group-hover:scale-110" />, title: 'Social Learning', desc: 'Collaborate with peers through study groups and discussions to enhance your learning experience.'
  },
  {
    icon: <Clock className="text-pink-400 w-12 h-12 transition-transform duration-200 group-hover:scale-110" />, title: 'Real-time Quiz Creation', desc: 'Create quizzes on-the-fly and receive instant feedback to improve your understanding and performance.'
  },
];

const InnovativeFeaturesSection: React.FC = () => (
  <section className="py-16 px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto">
    <div className="text-center mb-12">
      <h2 className="text-3xl sm:text-4xl font-extrabold text-white">Innovative Learning Features</h2>
      <p className="mt-4 text-xl text-gray-300 max-w-2xl mx-auto">
        Discover a suite of powerful tools designed to enhance your learning experience.
      </p>
    </div>
    <Swiper
      modules={[Navigation, Pagination, A11y]}
      spaceBetween={32}
      slidesPerView={1}
      navigation
      pagination={{ clickable: true }}
      breakpoints={{
        640: { slidesPerView: 2 },
        1024: { slidesPerView: 3 },
        1280: { slidesPerView: 4 },
      }}
      loop
      className="!pb-12"
    >
      {features.map((f, i) => (
        <SwiperSlide key={i}>
          <div className="flex flex-col items-center group w-full px-4 py-8">
            <div className="mb-3">{f.icon}</div>
            <div className="text-base font-bold text-white text-center mb-1 leading-tight">{f.title}</div>
            <div className="text-gray-400 text-sm text-center leading-snug">{f.desc}</div>
          </div>
        </SwiperSlide>
      ))}
    </Swiper>
  </section>
);

export default InnovativeFeaturesSection; 